### PR TITLE
Build from fpbioimage repo

### PR DESCRIPTION
**Pull request by jburel**
Build from fpbioimage repo

**do not merge this PR**

cc @mfantham @will-moore

### CODE REVIEW

**Comment by sbesson** [comment]
Is this still valid or should we close?

**Comment by jburel** [comment]
This is the only we have at the moment to use the non release build
I did not have time to work on it
but since there is not much activity on the repo 
We can close it for the time being

**Comment by jburel** [comment]
Re-opening this PR so we can test the recent changes

**Comment by jburel** [comment]
No longer needed with the new infrastructure on FPBioimage side

**Comment by will-moore** [comment]
It occurred to me that if we're working somewhere with poor internet connection (or none, e.g. workshop ) then we won't be able to rely on FPBioimage binaries being served remotely.
Is that OK?

**Comment by jburel** [comment]
Poor connection or no connection at all is something we will need to consider

**Pull request closed without merging**
